package se.wegelius.svbulkmail.model;
// Generated Mar 29, 2016 8:03:14 PM by Hibernate Tools 4.3.1



/**
 * CorruptedMail generated by hbm2java
 */
public class CorruptedMail  implements java.io.Serializable {


     private Integer corruptedMailId;
     private String corruptedMail;
     private String corruptedMailMsg;

    public CorruptedMail() {
    }

    public CorruptedMail(String corruptedMail, String corruptedMailMsg) {
       this.corruptedMail = corruptedMail;
       this.corruptedMailMsg = corruptedMailMsg;
    }
   
    public Integer getCorruptedMailId() {
        return this.corruptedMailId;
    }
    
    public void setCorruptedMailId(Integer corruptedMailId) {
        this.corruptedMailId = corruptedMailId;
    }
    public String getCorruptedMail() {
        return this.corruptedMail;
    }
    
    public void setCorruptedMail(String corruptedMail) {
        this.corruptedMail = corruptedMail;
    }
    public String getCorruptedMailMsg() {
        return this.corruptedMailMsg;
    }
    
    public void setCorruptedMailMsg(String corruptedMailMsg) {
        this.corruptedMailMsg = corruptedMailMsg;
    }




}


